######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 14 12:39:51 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += wry.h
SOURCES += wry.cpp
